import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
const inter = Inter({ subsets: ["latin"] });
import Appstate from "@/context/appState";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Appstate>
      <div className="min-h-screen bg-gradient-to-r from-purple-600 to-pink-500 text-white">
        <Navbar/>
        {children}
      </div>
      </Appstate>
        </body>
    </html>
  );
}
