/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/K5EXWW1Y8iL
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div
      className="min-h-screen bg-gradient-to-b from-[#9b30ff] to-[#800080] text-white">
      <nav className="flex justify-between items-center p-4">
        <div className="flex items-center space-x-2">
          <DogIcon className="h-8 w-8" />
          <span className="text-xl font-semibold">Puppy Love</span>
        </div>
        <div className="flex space-x-4">
          <Link className="hover:underline" href="#">
            Home
          </Link>
          <Link className="hover:underline" href="#">
            Credits
          </Link>
          <Link className="hover:underline" href="#">
            Statistics
          </Link>
          <SettingsIcon className="h-6 w-6" />
        </div>
      </nav>
      <div className="px-4 py-20">
        <h1 className="text-8xl font-bold mb-4">Dating season</h1>
        <h2 className="text-6xl font-bold mb-4">Try your luck</h2>
        <p className="text-lg mb-8">
          Puppy love is the Dating App of IIT Kanpur built by the Programming Club. Try your luck. Happy Dating!
        </p>
        <div className="flex space-x-4">
          <Button className="bg-white text-[#9b30ff] hover:bg-gray-100">Sign Up</Button>
          <Button className="bg-transparent hover:bg-white/10">Log In</Button>
        </div>
      </div>
    </div>)
  );
}


function DogIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5" />
      <path
        d="M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5" />
      <path d="M8 14v.5" />
      <path d="M16 14v.5" />
      <path d="M11.25 16.25h1.5L12 17l-.75-.75Z" />
      <path
        d="M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
    </svg>)
  );
}


function SettingsIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>)
  );
}
